# Site settings
title: Code for Nürnberg-Fürth
email: opendata@himsel.me
description: > # this means to ignore newlines until "baseurl:"
  Jede Woche treffen sich in ganz Deutschland „Code for Germany“ Teams, die gemeinsam an nützlichen Anwendungen und Visualisierungen rund um offene Daten und digitale Werkzeuge für Bürgerinnen arbeiten.
  Lokale Gruppen, bestehend aus Programmiererinnen, Designern und Open Data Interessierten, erproben, wie Code und Software dabei helfen können ihre Stadt und Nachbarschaft zu verbessern.
  Auch in Nürnberg besteht seit dem Jahr 2023 eine Gruppe aus interessierten Nutzern, die sich „Code for Nürnberg“ nennt.
baseurl: "" # the subpath of your site, e.g. /blog, change when you fork the repo from Code for Nürnberg!
url: "opendata-nuernberg.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: ["sbquo", "lsquo", "bdquo", "ldquo"]
permalink: /:categories/:year/:month/:day/:title/
keywords:
  - "Nürnberg"
  - "Fürth"
  - "Open Data"
  - "Offene Daten"
  - "Code"
  - "Code for Nürnberg"
  - "E-Government"
  - "Transparenz"
  - "Bürgerbeteiligung"
  - "Stadtentwicklung"
  - "Visualisierung"
  - "Stadt"
  - "Demokratie"
repository: opendata-nuernberg/opendata-nuernberg.github.io
remote_theme: chrisrhymes/bulma-clean-theme@eb8d08e78e150b4dc5dd37742cb9f6237e0b46a7
plugins:
  - jekyll-feed

footer_menu: footer_links

# gem jekyll-seo-tag
social:
  name: Code for Nürnberg-Fürth
  links:
    - https://github.com/opendata-nuernberg
lang: de_DE

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
